version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    container_name: es
    environment:
      - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  api:
    build: .
    ports:
     - "5000:5000"